version: '3.1'
name: odoo_v16
services:
  web:
    container_name: web
    build: .
    depends_on:
      - db
    volumes:
      - ./odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    ports:
      - "8069:8069"
    env_file:
      - .env
    environment:
      - HOST=db
      - USER=${POSTGRES_USER}
      - PASSWORD=${POSTGRES_PASSWORD}
  db:
    container_name: db
    image: postgres:15
    env_file:
      - .env
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./odoo-db-data:/var/lib/postgresql/data/pgdata
